#!/bin/sh

cd $(dirname $0)

INTMAP=$(readlink -m "$(dirname $0)/../../tools/intmap.py")

if ! [ -f "$INTMAP" ]; then
    echo "Error: Failed to find '$INTMAP' script."
    exit 1
fi

SRC_DIR=../../data/Human/raw

OUT_DIR=../../data/Human

for ((i = 0; i <= 114; ++i)); do
    echo "Processing 'human_$i'..."
    $INTMAP $SRC_DIR/human_$i.data $SRC_DIR/human_$i.graph \
            $OUT_DIR/human_$i.data $OUT_DIR/human_$i.graph \
            $OUT_DIR/human_$i.keymap
done
