#!/bin/sh

# Usage: ./process_all
#
# FIXME: Move all reduction and processing scripts into a Makefile. This would
# allow much of the work to be done in parallel.

# DBLP dataset
./DBLP/reduce

# Human dataset
./Human/process
./Human/reduce

# Synthetic dataset
./Synthetic/process
./Synthetic/reduce

# Traffic dataset
./Traffic/reduce

# Twitter dataset
./Twitter/process
./Twitter/reduce

# Wikipedia dataset
./Wikipedia/process
./Wikipedia/reduce
