#!/bin/sh

# Reduces the DBLP datasets to 1000 nodes each.

cd $(dirname $0)

GRAPH=../../data/Wikipedia/wiki-links.graph

mkdir -p ../../data/Wikipedia/reduced

COUNT=1000

YEARS='2008 2009 2010 2011'

for year in $YEARS; do
    DATA=../../data/Wikipedia/wiki-views-$year-day.data
    DATA_REDUCED=../../data/Wikipedia/reduced/$COUNT.wiki-views-$year-day.data
    GRAPH_REDUCED=../../data/Wikipedia/reduced/$COUNT.wiki-views-$year-day.graph

    if ! [ -f $DATA_REDUCED ] || ! [ -f $GRAPH_REDUCED ]; then
        echo "Reducing 'Wikipedia $year' to $COUNT nodes..."
        ../../tools/reduce.py $DATA $GRAPH $DATA_REDUCED $GRAPH_REDUCED --count $COUNT
    fi
done
