#!/bin/sh

# Reduces the Wikipedia dataset to more manageable sizes.
#
# Usage:
#     $ ./reduce
# or, because this may take a long time, use
#     $ ./reduce &> progress &

cd $(dirname $0)

BASE=../../data/Wikipedia

DATA=$BASE/wiki-views-2008-day.data
GRAPH=$BASE/wiki-links.graph

REDUCED_DIR=$BASE/reduced

# Graph reduction tool
REDUCE=../../tools/reduce_many

mkdir -p $REDUCED_DIR

YEARS='2008 2009 2010 2011'

for year in $YEARS; do
    echo "Reducing Wikipedia page views for $year..."
    $REDUCE $BASE/wiki-views-$year-day.data $GRAPH \
        $REDUCED_DIR/wikipedia-$year.%d.data $REDUCED_DIR/wikipedia-$year.%d.graph \
        -n 50 100 250 500 1000 10000 50000 100000
done
