#!/bin/env python2.7
"""
Decompresses a network using the Spectral Graph Fourier method.

Author: Ali Hajimirza (ali@alihm.net)
"""
import fourier
import argparse
import sys
from os import path

sys.path.append(path.dirname(path.realpath(path.join(__file__, '../..'))))
import tools.graph_reader as graph_reader

parser = argparse.ArgumentParser(
    description="Decompresses a network using the Spectral Graph Fourier method."
    )
parser.add_argument("graph", type=argparse.FileType("rb"),
    help="Input graph file.")
parser.add_argument("signal", type=argparse.FileType("rb"),
    help="Input signal values.")

if __name__ == '__main__':
    args = parser.parse_args()

    graph = graph_reader.read_graph(args.graph, len(data))

    if args.budget == 0:
        args.budget = len(data)/2

    fourier.decompress_graph(graph, args.signal)

