#!/bin/env python2.7
"""
Takes from standard input a list of node values and outputs a list of randomized
node values in the range [0 .. 100,000) to standard output.

Author: Jason White
"""
import sys
from random import shuffle

if __name__ == "__main__":
    try:
        finput = sys.stdin
        foutput = sys.stdout

        # Read in all values and shuffle
        ids = []
        values = []

        for line in finput:
            vals = line.strip().split(',')
            ids.append(vals[0])
            values.append(vals[1])

        shuffle(values)

        # Write back
        for i,v in enumerate(values):
            foutput.write("%s,%s\n" % (ids[i], v))

    except KeyboardInterrupt:
        pass
