#!/bin/sh

# Reduces the Twitter dataset to more manageable sizes.
#
# Usage:
#     $ ./reduce
# or, because this may take a long time, use
#     $ ./reduce &> progress &

cd $(dirname $0)

BASE=../../data/Twitter

DATA=$BASE/twitter.data
GRAPH=$BASE/twitter.graph

REDUCED_DATA=$BASE/reduced/twitter_%d.data
REDUCED_GRAPH=$BASE/reduced/twitter_%d.graph

# Graph reduction tool
REDUCE=../../tools/reduce_many

mkdir -p $REDUCED_DIR

$REDUCE $DATA $GRAPH $REDUCED_DATA $REDUCED_GRAPH \
    -n 50 100 250 500 1000 10000 50000 100000

