#!/bin/sh

# Reduces the DBLP datasets to 1000 nodes each.

cd $(dirname $0)

DATA=../../data/Twitter/twitter.data
GRAPH=../../data/Twitter/twitter.graph

mkdir -p ../../data/Twitter/reduced

COUNT=1000

DATA_REDUCED=../../data/Twitter/reduced/$COUNT.twitter.data
GRAPH_REDUCED=../../data/Twitter/reduced/$COUNT.twitter.graph

if ! [ -f $DATA_REDUCED ] || ! [ -f $GRAPH_REDUCED ]; then
    echo "Reducing 'twitter' to $COUNT nodes..."
    ../../tools/reduce.py $DATA $GRAPH $DATA_REDUCED $GRAPH_REDUCED --count $COUNT
fi
